# Generated by Django 3.1.5 on 2021-02-19 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, verbose_name='Symbol')),
                ('market_symbol', models.CharField(default='^GSPC', max_length=10, verbose_name='Market Symbol')),
                ('security_name', models.CharField(max_length=64, verbose_name='Security Name')),
                ('gics_industry', models.CharField(blank=True, max_length=64, null=True, verbose_name='GICS Industry')),
                ('gics_sub_industry', models.CharField(blank=True, max_length=64, null=True, verbose_name='GICS Sub-Industry')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'unique_together': {('symbol', 'market_symbol')},
            },
        ),
        migrations.CreateModel(
            name='AssetPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Date and Time')),
                ('high', models.DecimalField(decimal_places=10, max_digits=15, verbose_name='High')),
                ('low', models.DecimalField(decimal_places=10, max_digits=15, verbose_name='Low')),
                ('open', models.DecimalField(decimal_places=10, max_digits=15, verbose_name='Open')),
                ('close', models.DecimalField(decimal_places=10, max_digits=15, verbose_name='Close')),
                ('volume', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Volume')),
                ('adj_close', models.DecimalField(decimal_places=10, max_digits=15, verbose_name='Adjusted Close')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset', to='assets.asset')),
            ],
            options={
                'verbose_name': 'Asset Price',
                'verbose_name_plural': 'Asset Prices',
                'unique_together': {('asset', 'datetime')},
            },
        ),
    ]
